### ISSUE TITLE
Google Play

### ISSUE THREAD

**Issue by alekseishaklov** [keepalivedev/KeepAlive#1]
**Expected behaviour**: opensource app may be downloaded from F-Droid or apk from Github
**Actual behaviour**: app may be downloaded from Google Play only
*Sorry*
![Screenshot_20231122-141302](https://github.com/keepalivedev/KeepAlive/assets/78877882/5a6e300f-5f0f-4a58-bcf6-e6f4f14232b9)
(Text in Russian: "unavailable in your country")

**Comment by keepalivedev** [comment]
This is my first time publishing an Android app so wasn't sure what people expect.  I've added the apk as a new Release https://github.com/keepalivedev/KeepAlive/releases/tag/1.0.3.  Also it was US only because I thought I needed translations but that does not seem to be the case.  I added all countries and will republish once Google approves the changes.  I will also look into adding it to the F-Droid store next week.  And I guess I'll try to be less fascist in the future?

**Comment by keepalivedev** [comment]
@alekseishaklov The app should be available in all countries now, can you confirm?

**Comment by alekseishaklov** [comment]
> This is my first time publishing an Android app so wasn't sure what people expect.  I've added the apk as a new Release https://github.com/keepalivedev/KeepAlive/releases/tag/1.0.3.  Also it was US only because I thought I needed translations but that does not seem to be the case.  I added all countries and will republish once Google approves the changes.  I will also look into adding it to the F-Droid store next week.  And I guess I'll try to be less fascist in the future?

Thanks for your answer and sorry for the misunderstanding. I'm just used to some developers not allowing me to download apps from my country. Dowloading is available at the moment.

P.S. Btw, I can help with the translation
