### ISSUE TITLE
feature req: wait time for gps location

### ISSUE THREAD

**Issue by nutpantz** [keepalivedev/KeepAlive#32]
The app does not seem to wait to get a gps location. There there should be a "wait for gps lock" time limit. Or maybe use last known location, and have the app have a "update location every X minutes" option (which might really eat battery)

**Comment by keepalivedev** [comment]
When using the Test Alert SMS button, pulling the location should be more or less instant since you are actively using your phone.  

The app is designed to first try to get the current location and, if that fails, it will try to get the last known location.  There is a 30 second timeout on getting the location and a 30 second timeout on geocoding the coordinates.  The app could be polling the location in the background however, as you mentioned, this would increase the battery usage.

**Comment by nutpantz** [comment]
Maybe a get gps location button or manual entry.  To set a default location for the app if it can't get location via gps. 

Maybe a poll location every X hours setting for those who move around a lot?

You don't want a lot of extra battery usage if not necessary.

**Comment by keepalivedev** [comment]
Can you open a new feature request for this and describe some potential use cases?

**Comment by nutpantz** [comment]
Sure.
