### ISSUE TITLE
What's the reason for 10 minute minimum?

### ISSUE THREAD

**Issue by r1bilski** [keepalivedev/KeepAlive#50]
**Is your feature request related to a problem? Please describe.**
I wonder what's the reason behind the 10 minute minimum. I'd like to set confirmation period that is shorter, but I cannot and having to go 10min+ seems arbitrary to me. Is there any particular reason for that?

**Describe the solution you'd like**
If there is no reason for the 10 minute minimum, then I'd suggest removing it altogether, and leave it up to the user to decide. Also I'd suggest adding a timepicker, similar to how timer apps do it, because inputing sub-hour times is a little difficult, given you have to work with fractures.

**Comment by keepalivedev** [comment]
Keep Alive was primarily designed to be used over longer time periods so, in order to save on battery, the initial alarm isn't an 'exact' alarm and Android can delay it by up to 15 minutes. During testing, if I set an alarm for less than 10 minutes in the future, it sometimes never went off at all.  Because the alarms aren't exact I didn't think using a time picker would make sense because it would imply that the timing is more granular than it actually is.

Also I haven't used it myself but I previously came across this app [Dead Man's Switch](https://play.google.com/store/apps/details?id=org.kleeschulte.android.tmw) that allows for shorter duration alarms in case that is better suited to your use case.
