### ISSUE TITLE
any plans to release on IOS? or at least android smart watches?

### ISSUE THREAD

**Issue by haleemyousef** [keepalivedev/KeepAlive#59]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problemis. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by keepalivedev** [comment]
I had originally wanted to make Keep Alive cross platform but unfortunately iOS apps are not allowed to send SMS messages without user interaction.  In order to do this on iOS there would need to be some external server infrastructure in order to send out the alert messages.

I hadn't thought about smart watches.  I did some testing and, at the very least, the UI would need to be redesigned as it doesn't fit on the smaller screen.  I am also not sure how the alerting would work as most watches rely on a paired phone to send SMS or phone calls.
