### ISSUE TITLE
Can't use test alert call without SMS

### ISSUE THREAD

**Issue by Lyverbe** [keepalivedev/KeepAlive#62]
**Describe the bug**
My plan doesn't include SMS so I did not allow the app to send SMS making sure I won't be accidentally charged.  It seems without this permission, I can't even use the 'Alert call' feature.

**Expected behavior**
Allowed to use the 'Alert call' feature even without SMS

**Smartphone:**
 - Device: Samsung S23
 - OS: Android 14
 - App Version: 1.1.4

**Comment by keepalivedev** [comment]
This wasn't a use case I had considered but as long as you do not add any SMS contacts then there won't be any SMS sent.  I understand your hesitation and wanting to make sure you don't get charged though.  I will look into making it so that it only requests SMS permissions if there is an SMS contact configured.

**Comment by keepalivedev** [comment]
This should be implemented in version 1.2.3.
