### ISSUE TITLE
Remove minimum time

### ISSUE THREAD

**Issue by aodhan-domhnaill** [keepalivedev/KeepAlive#8]
Cool app! I would like to use this as a safety app so when I workout alone I can text the facility manager if something bad happens. I can't set a period shorter than 10min though.

Would you accept a PR removing this 10 min minimum?

**Comment by keepalivedev** [comment]
Keep Alive was primarily designed to be used over longer time periods so, in order to save on battery, the initial alarm isn't an 'exact' alarm and Android can delay it by up to 15 minutes.  During testing, if I set an alarm for less than 10 minutes in the future, it sometimes never went off at all.  I would be fine with adding functionality to allow for shorter duration alerting if you or anyone want to open a PR.  

Also I haven't used it myself but I previously came across this app [Dead Man's Switch](https://play.google.com/store/apps/details?id=org.kleeschulte.android.tmw) and it looks like it might be better suited for your use case.

**Comment by aodhan-domhnaill** [comment]
Yeah. Dead Man's Switch is perfect. Thanks! Closing
